### ISSUE TITLE
Support .NET 6.0

### ISSUE THREAD

**Issue by BeastLe9enD** [Itiviti/gradle-dotnet-plugin#11]
Hey,
It would be nice to have a NET 6.0 version even if the official version isn't yet, as many developers, including myself, are already working on a NET 6.0 application. 
This shouldn't take too many steps, as only one version number actually needs to be changed.
Thanks in advance!:)

**Comment by ngyukman** [comment]
I finally have time to fix the build pipeline after Olympic 🥇

**Comment by ngyukman** [comment]
Version 1.8.0 is released
