### ISSUE TITLE
Target framework in ProjectFileParser.csproj

### ISSUE THREAD

**Issue by ndw** [Itiviti/gradle-dotnet-plugin#13]
Hello,

Apologies if these are naive questions. I'm trying to configure a C# project to build, test, and release it with Gradle. The project builds fine in Ryder, but I want to be able to automate the process.

I've installed the `com.itivitiy.dotnet` plugin version 1.8.0 but when I run `gradle dotNetBuild` I get:

```
* What went wrong:
Could not determine the dependencies of task ':dotnetBuild'.
> Failed to calculate the value of task ':dotnetBuild' property 'sources'.
   > Failed to parse project, output: /usr/local/share/dotnet/sdk/5.0.301/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5):
error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a
version of the .NET SDK that supports .NET 6.0.
[/Users/ndw/Projects/xmlresolver/cs/build/tmp/dotnet/ProjectFileParser.csproj]
     , error:
     The build failed. Fix the build errors and run again.
```

The `build/tmp/ProjectFileParser.csproj` file does indeed specify net6.0:

```
    <TargetFrameworks>netcoreapp3.1;net5.0;net6.0</TargetFrameworks>
```

but I can't tell how or why `ProjectFileParser.csproj` is constructed, nor can I tell why `net6.0` is included in it. There's no reference to `net6.0` (or even `net6`) anywhere in the project sources.

I expect this is user error or user misconfiguration, but any clues would be most eagerly accepted.

**Comment by ngyukman** [comment]
hi @ndw, could you please try with version 1.7.2 instead of 1.8.0?
the plugin 1.8.0 has some issues to support for net core 3.0 and 6.0 currently

**Comment by ndw** [comment]
Thank you! With 1.7.2, the files seem to parse correctly.
