### ISSUE TITLE
Building multiple solutions

### ISSUE THREAD

**Issue by ndw** [Itiviti/gradle-dotnet-plugin#15]
Hello, me again with more naive questions.

Building with `gradlew dotnetBuild` now produces an output for one of the solutions, but only one of them. There are four in the project, the code, some data, the unit tests, and a sample app that I'm just using for testing.

The code builds, but not the data. I was pleased that I was able to load the `.nupkg` file in another project, but it can't finish the import because of the dependency on the data assembly.

**Comment by ngyukman** [comment]
hi @ndw 

depending on the structure, you might have two different approach
1. having a .sln including multiple csproj, so building one solution builds multiple projects at once, and you could have proper project references as well
2. use sub-project feature in gradle as mentioned in https://docs.gradle.org/current/userguide/intro_multi_project_builds.html

**Comment by ndw** [comment]
I'd just as soon avoid sub-projects. Ultimately, these all go together and don't need to stand alone.

Before I posted the question, I looked in the `.sln` file to see if I could work out how to tell it to build more than one `.csproj`, but the different projects all appear to be referenced the same way:

```

Microsoft Visual Studio Solution File, Format Version 12.00
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "XmlResolver", "XmlResolver\XmlResolver.csproj", "{B347954F-8FC1-49A1-AF2E-1C46F030B8AC}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "UnitTests", "UnitTests\UnitTests.csproj", "{EB15F220-858B-4661-B5E1-25BAE467B77D}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "SampleApp", "SampleApp\SampleApp.csproj", "{44D45D23-B2A1-4EF2-B838-6B019FE1C7FF}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "XmlResolverData", "XmlResolverData\XmlResolverData.csproj", "{F3EDFC12-6E8B-46BC-A56B-DA7EA373D4D8}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{B347954F-8FC1-49A1-AF2E-1C46F030B8AC}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{B347954F-8FC1-49A1-AF2E-1C46F030B8AC}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{B347954F-8FC1-49A1-AF2E-1C46F030B8AC}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{B347954F-8FC1-49A1-AF2E-1C46F030B8AC}.Release|Any CPU.Build.0 = Release|Any CPU
		{EB15F220-858B-4661-B5E1-25BAE467B77D}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{EB15F220-858B-4661-B5E1-25BAE467B77D}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{EB15F220-858B-4661-B5E1-25BAE467B77D}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{EB15F220-858B-4661-B5E1-25BAE467B77D}.Release|Any CPU.Build.0 = Release|Any CPU
		{44D45D23-B2A1-4EF2-B838-6B019FE1C7FF}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{44D45D23-B2A1-4EF2-B838-6B019FE1C7FF}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{44D45D23-B2A1-4EF2-B838-6B019FE1C7FF}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{44D45D23-B2A1-4EF2-B838-6B019FE1C7FF}.Release|Any CPU.Build.0 = Release|Any CPU
		{F3EDFC12-6E8B-46BC-A56B-DA7EA373D4D8}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{F3EDFC12-6E8B-46BC-A56B-DA7EA373D4D8}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{F3EDFC12-6E8B-46BC-A56B-DA7EA373D4D8}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{F3EDFC12-6E8B-46BC-A56B-DA7EA373D4D8}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
EndGlobal
```

I don't see anything in there that looks like it says "build XmlResolver" but not the others.

If it's obvious to you what I need to do to make this build all four projects, please do tell. Otherwise, I guess this isn't really a plugin bug and thank you for taking the time to reply!

**Comment by ngyukman** [comment]
Sorry I misunderstood your original question, to build only one csproj you might set solution to the csproj , and you might use project properties to control which csproj to build

```
dotnet {
    solution = "src/${project.property('csproj')}"
}```

Then build using ./gradlew dotnetBuild -Pcsproj=(path to csproj to build)

**Comment by ndw** [comment]
No, I think you understood, I just confused you with a poorly written comment. Sorry about that. I'm not sure I really understand the C# terminology exactly.

I have a directory containing `build.gradle` and under it is a "solution" (`XmlResolver/XmlResolver.sln`, that's the file I showed above) that consists of four "projects", (`XmlResolver/XmlResolver/XmlResolver.csproj`, `XmlResolver/XmlResolverData/XmlResolverData.csproj`, `XmlResolver/UnitTests/UnitTests.csproj`, and `XmlResolver/SampleApp/SampleApp.csproj`).

I want `gradle dotNetBuild` to make all of them, but today it *only* builds `XmlResolver/XmlResolver/XmlResolver.csproj`

**Comment by ndw** [comment]
I take that back. I removed all the `bin` and `obj` directories and ran the build again. It does repopulate the build outputs for each project, but it only makes one `.nupkg` file. The `XmlResolver-0.0.1.nupkg` file requires the data assembly, so (I think) I need `XmlResolverData-0.0.1.nupkg` as well. (I don't actually need a NuGet package for `SampleApp` because that's just a playground for debugging and trying to learn about the C# APIs and obviously I don't need to package the unit tests.)

I would like the resolver and its data to be separate assemblies, but I can probably live with making them a single assembly if it's not possible to make both NuGet packages.

**Comment by ngyukman** [comment]
you need to have `<GeneratePackageOnBuild>True</GeneratePackageOnBuild>` in csproj in order to generate nupkg on build
I think it is missing in your data project now

**Comment by ndw** [comment]
That was it. Thank you. And thank you very much for your patience!
