### ISSUE TITLE
Configuring build versions

### ISSUE THREAD

**Issue by ndw** [Itiviti/gradle-dotnet-plugin#17]
Once again, I apologize if what's really going on here is that I'm confused about how gradle works.

I'm trying to integrate into a project that already has a build script for other tasks. For historical reasons, there are two properties, `acmeMajorVersion` and `acmeMinorVersion` that are used to track the product version (instead of the `version` property). For better or worse, that's the way it is and I'm hoping I don't have to try to fix that globally.

I tried:

```
build {
  version = "${acmeMajorVersion}.${acmeMinorVersion}.0"
  packageVersion = "${acmeMajorVersion}.${acmeMinorVersion}.0"
}
```

And that didn't work. I tried setting things in various places (`settings.gradle`, `gradle.properties`, etc.) to no avail. Thoroughly confused, I thought I'd start with what is documented as working:

```
build {
  version = project.version
  packageVersion = project.version
}
```

But that doesn't work either:

```
* Where:
Build file '/Volumes/Acme/src/acme/acmedev/build.gradle' line: 120

* What went wrong:
A problem occurred evaluating root project 'Saxon'.
> Cannot get property 'version' on null object
```

What's *really* odd is that if I put a print statement before the dotnet configuration block:

```
println("${project.acmeMajorVersion}, ${acmeMajorVersion}, ${project.version}")
```

that prints "11, 11, unspecified" *before* the failure. 

Is there some way that I can get the values I want inserted into the build script?

**Comment by ngyukman** [comment]
Hi, can you check with --stacktrace in your gradle command to verify where does the null pointer coming from?
it could be a bug in the plugin but you might also try setting project.version by acmeMajorVersion and acmeMajorVersion as well

**Comment by ndw** [comment]
I'll try to get a stack trace asap. I just started another build and they take a while.

 I'm thinking, because of #18, that I might end up having to run the `dotnet` commands in an `Exec` task.

**Comment by ndw** [comment]
Sorry I dropped the ball on this. Focus was on getting a release out and I think I just worked around it.
