### ISSUE TITLE
Dealing with a dotnet build that is configured by tasks?

### ISSUE THREAD

**Issue by ndw** [Itiviti/gradle-dotnet-plugin#18]
The complicated build I alluded to in the previous issue is even more complicated :-)

Part of the build actually generates some code, including the `.csproj` and `.sln` files that I want to use to build the release. Unfortunately, this doesn't work:

```
task generate_the_csharp_config() {
  ...
}
dotnetBuild.dependsOn generate_the_csharp_config
```

Or, rather, it sort of works. It is true that `generate_the_csharp_config` runs before `dotnetBuild`, but the gradle script fails during configuration if the `.csproj` and `.sln` files don't already exist.

Is it possible to work around this?

**Comment by ngyukman** [comment]
indeed the plugin does not support generated .sln and .csproj before the gradle execute, is there any reason it requires to be generated? .csproj allows to include all sources from a dir, thus normally you don't need to have it auto-generated

**Comment by ndw** [comment]
Almost all the C# code is generated, so the whole "source" tree is in fact under `build` and doesn't exist at all until a whole bunch of code generation has happened. The `.csproj` and `.sln` files are actually pretty static, but they aren't going to be in the `build` subdirectory on a clean build. Looks like `Exec` tasks here I come...

**Comment by ngyukman** [comment]
then you could just avoid `.csproj` and `.sln` be generated
in our use case we also have similar generated source codes but we keep having the static `.csproj` and `.sln` in the repo

**Comment by ndw** [comment]
There would still need to be a task to move them under `build`, or there'd have to be a separate build directory that was partly under version control and partly not. I suppose that could work, but it's very appealing.

(None of this is intended as criticism of the plugin, I hasten to add, I'm aware that this is an unusually complex build setup.)
