### ISSUE TITLE
TestOutputXml path on non-Windows environment

### ISSUE THREAD

**Issue by Azurelol** [Itiviti/gradle-dotnet-plugin#20]
Hello. When running the tests on the CI on a non-Windows environment, the double-quotes used here lead to the path being set incorrectly. For example, on a Jenkins build, the tests are being output like this:

`$Root / $Solution / $TestProject / bin / release / net5.0 / "$CI/$Root/build/reports/nunit"`

When I would expect them to be:

`$Root / build / reports / nunit`

I believe it comes from the double quotations here:
https://github.com/Itiviti/gradle-dotnet-plugin/blob/14c595560e564b2aeb3211201fae223a90c1fbed/src/main/kotlin/com/itiviti/tasks/DotnetTestTask.kt#L42

**Comment by ngyukman** [comment]
hi, it is probably due to powershell / command prompt and linux shell all have different behavior on handling double quotes
and indeed in command args, we might not even need a double quote
