### ISSUE TITLE
dotnetNugetPush throws error while trying to publish duplicate

### ISSUE THREAD

**Issue by vinoth-karunanithy** [Itiviti/gradle-dotnet-plugin#6]
When we try to publish duplicate nuget package, we receive the below error.

**_info : To skip already published packages, use the option --skip-duplicate
error: Response status code does not indicate success: 409 (Conflict)._**

I believe we have an argument --skip-duplicate to avoid such error. It could be customized such that a boolean variable to accept skipping error can be introduced and that would help in avoiding error scenarios during nuget push. 

This could be made optional and the default value for the boolean could be false. Hence when made true, the duplicate error would be skipped, else the error would be highlighted in gradle.

Kindly look into the possibility of implementing the above fix.

**Comment by ngyukman** [comment]
hi @vinoth-karunanithy 

what is your use case for skipping the duplicate check? From the official document it is only useful when you are pushing multiple packages while some of them have conflict

in gradle you are already able to skip the publish task easily, either by not putting it into the task list or use `-x dotnetNugetPush`

**Comment by vinoth-karunanithy** [comment]
Hi @ngyukman ,

The gradle is applied on top of multiple projects, where only my project is just the dotnet project. All other projects are of various technologies and is currently working. So when a Publish happens there could be scenario that same package will be tried to push into the nuget repository. There is no such mechanism to check the existing packages in the nuget repository. 

Basically if the package is new, then it should be published to nuget repo. If not, there shouldn't be any error, as the error could stop the other project's publish.

PS: Seriously I am new to gradle, I might be missing something.
Please advise, is there anything that I missed or do you have any workaround for getting this behavior.

Thanks

**Comment by ngyukman** [comment]
hi @vinoth-karunanithy 

I am not sure hiding this error is useful in your use case
from the official document it is useful when you need to generate multiple package and only some of them can be published

in your case it should be rather to make sure to do not run publish task on the desired project that you want to publish (java's maven publish has a similar behavior here)
you can control by injecting project properties `-PpublishToNuget=false` and add `publish.enabled = project.properties.publishToNuget` in dotnet project's build.gradle
or skip it by adding `-x :sub-project-id:dotnetNugetPush` in command line argument
so you will not miss a case that when you wish to push to nuget but forget to update the version number

**Comment by vinoth-karunanithy** [comment]
Ok Thanks @ngyukman. 

I somehow managed to achieve the feature with some work around. Hope that should be fine for now.
Thanks for your prompt support. :)
